// alert('Hello Javascript!');
console.log('I am a conslole log');
var myVariable = 'Hi vars!';
console.log(myVariable);
console.log({key1:1, key2:2});
console.table({key1:"string value", key2:2});
console.error('you have made an error :D');
// console.clear();
console.warn("i'm warning you!");
console.log('You know what time it is!');
console.time("That's all folks!");
  console.log('I need more time!');
  console.log('I need more time!');
  console.log('I need more time!');
  console.log('I need more time!');
  console.log('I need more time!');
  console.log('I need more time!');
  console.log('I need more time!');
console.timeEnd("That's all folks!");
